name: BBJumpPads
version: 1.01
main: com.beanblockz.jumppads.JumpPads
author: sponges.io
description: Jump pads plugin for beanblockz.com
commands:
  bbjumppads:
    aliases: [jumppads, jp]
    description: Main command
permissions:
  bbjumppads.jumppads.use:
    default: false
  bbjumppads.trampolines.use:
    default: false
  bbjumppads.version:
    default: false
  bbjumppads.reload:
    default: false